/**
 * Данные для посева закладок
 */

export const DUMMY_BOOKMARK_CATEGORIES = [
  { id: "ktGDhX", parent_id: "0", title: "Несортированные", icon: "Inbox", position: 0 },
  { id: "wxiqnC", parent_id: "0", title: "Корзина", icon: "Trash", position: 0 },
  { id: "0", parent_id: "", title: "Системные", icon: "", position: -2 },
  { id: "wTOx", parent_id: "", title: "Работа", icon: "", position: -1 },
  { id: "tVhm", parent_id: "wTOx", title: "Инструменты", icon: "Folder", position: 2 },
  { id: "IpYb", parent_id: "", title: "Основное", icon: "", position: -1 },
  { id: "4x3o", parent_id: "IpYb", title: "Рецепты", icon: "Folder", position: 3 },
  { id: "7i95", parent_id: "IpYb", title: "Игры", icon: "Rocket", position: 0 },
  { id: "mKgw", parent_id: "IpYb", title: "Хочу прочитать", icon: "Folder", position: 6 },
  { id: "V8dU", parent_id: "IpYb", title: "Хочу посмотреть", icon: "Film", position: 7 },
  { id: "Arkq", parent_id: "wTOx", title: "Документации", icon: "Folder", position: 3 },
  { id: "7LSI", parent_id: "wTOx", title: "Хочу изучить", icon: "Folder", position: 4 },
  { id: "HWt3", parent_id: "wTOx", title: "Letoile", icon: "UserGroup", position: 0 },
  { id: "l15e", parent_id: "IpYb", title: "Инструменты", icon: "Folder", position: 2 },
  { id: "ghhl", parent_id: "IpYb", title: "MyApp", icon: "Folder", position: 1 },
  { id: "F6O2", parent_id: "IpYb", title: "Хочу пересмотреть", icon: "Film", position: 8 },
  { id: "Vzgd", parent_id: "IpYb", title: "Хочу поиграть", icon: "Folder", position: 5 },
  { id: "gKdY", parent_id: "IpYb", title: "Sur Ron", icon: "Folder", position: -1 },
  { id: "j5cG", parent_id: "IpYb", title: "Велосипед", icon: "Folder", position: -1 },
  { id: "ie4p", parent_id: "IpYb", title: "LG", icon: "Folder", position: -1 },
  { id: "wai5", parent_id: "IpYb", title: "OnePlus 13R", icon: "Folder", position: -1 },
  { id: "SVSZ", parent_id: "IpYb", title: "Кофе", icon: "Folder", position: -1 },
  { id: "euMD", parent_id: "IpYb", title: "AI", icon: "Folder", position: -1 },
  { id: "eH1u", parent_id: "wTOx", title: "Поиск 2025", icon: "Folder", position: -1 },
];

export const DUMMY_BOOKMARK_TAGS = [
  { id: "GE20b", title: "Срочно" },
  { id: "7t78v", title: "Крылышки" },
  { id: "8GN6p", title: "Xbox" },
  { id: "fM6YW", title: "Курица" },
  { id: "x78IZ", title: "Ребрышки" },
  { id: "NSMjl", title: "Playstation" },
  { id: "ent7g", title: "Node" },
  { id: "xU4PD", title: "SQLite" },
  { id: "1fFZi", title: "Javascript" },
  { id: "Wsw8g", title: "JSON" },
  { id: "ulV4b", title: "Свинина" },
  { id: "S7XFX", title: "Картофель" },
  { id: "7Mjrx", title: "nvm" },
  { id: "gY5YF", title: "SQL" },
  { id: "Pe8tG", title: "Git" },
  { id: "CyVhI", title: "Хочу приготовить" },
  { id: "mgjD0", title: "Сэндвич" },
  { id: "ZJf5O", title: "Стейк" },
  { id: "BXaLC", title: "Helldivers 2" },
  { id: "ljFAI", title: "Где кататься" },
  { id: "HY1CR", title: "Фасоль" },
  { id: "e0C39", title: "Яйца" },
  { id: "ymCVP", title: "Кофе" },
  { id: "IN7Ob", title: "Ростбиф" },
  { id: "XtI6V", title: "Android" },
];

export const DUMMY_BOOKMARKS = [
  {
    id: "dSMicJ",
    category_id: "ktGDhX",
    title: "Полный гайд на Резюме в IT - Как Правильно составить резюме программисту?",
    url: "https://www.youtube.com/watch?v=mU-MghntMxg",
    description: "Enjoy the videos and music that you love, upload original content and share it all with friends, family and the world on YouTube.",
    tags: [],
    preview: "",
    created_at: "2025-06-30 02:38:20",
    updated_at: "2025-06-30 02:38:27",
    transition_counter: 1,
    favorite: false,
  },
  {
    id: "UIje1I",
    category_id: "ktGDhX",
    title: " Nest + Typia = Nestia. Доминация Typescript",
    url: "https://www.youtube.com/watch?v=eAFq35Z6z5I",
    description: "Enjoy the videos and music that you love, upload original content and share it all with friends, family and the world on YouTube.",
    tags: [],
    preview: "",
    created_at: "2025-06-30 02:37:45",
    updated_at: "2025-06-30 02:38:00",
    transition_counter: 1,
    favorite: false,
  },
  {
    id: "qRN4eu",
    category_id: "ktGDhX",
    title: "\"Star Rail LIVE 2025\" Concert Full Recording | Honkai: Star Rail - YouTube",
    url: "https://www.youtube.com/watch?v=FAckVYINs8E",
    description: "The Official Recording of \"Star Rail LIVE\" Honkai: Star Rail Concert 2025 is Online — The Cosmos Resonates for You!Attention, passengers, the Express is abou...",
    tags: [],
    preview: "https://i.ytimg.com/vi/FAckVYINs8E/maxresdefault.jpg",
    created_at: "2025-05-04 21:51:58",
    updated_at: "2025-05-04 21:52:00",
    transition_counter: null,
    favorite: false,
  },
  {
    id: "NUjbfo",
    category_id: "ktGDhX",
    title: "Lenovo Legion Y700 Как настроить планшет , установить русский язык , удалить китайские приложения - YouTube",
    url: "https://www.youtube.com/watch?v=EsyqqjnwOws",
    description: "Lenovo Legion Y700 Китайская версия с китайской оригинальной прошивкой с русским языком .Настрока планшета,установка русского языка,удаление китайских прилож...",
    tags: [],
    preview: "https://i.ytimg.com/vi/EsyqqjnwOws/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGFcgWChlMA8=&rs=AOn4CLBUFjk2kmMryRmpuJJJ90k721l0HQ",
    created_at: "2025-03-14 13:51:00",
    updated_at: "2025-03-14 13:51:03",
    transition_counter: 2,
    favorite: false,
  },
  {
    id: "MmD8cr",
    category_id: "ktGDhX",
    title: "Встреча христианского клуба НИУ ВШЭ | иерей Павел Островский - YouTube",
    url: "https://www.youtube.com/watch?v=ZN7YTvMaw0w",
    description: "Как найти ответы на сложные вопросы о вере? Где обсудить важные темы на простом, доступном языке? На встрече с иереем Павлом Островским в Культурном центре «...",
    tags: [],
    preview: "https://i.ytimg.com/vi/ZN7YTvMaw0w/maxresdefault.jpg",
    created_at: "2025-03-08 22:28:58",
    updated_at: "2025-03-08 22:29:00",
    transition_counter: null,
    favorite: false,
  },
  {
    id: "pIDIZR",
    category_id: "ktGDhX",
    title: "Дмитрий Лаврик - YouTube",
    url: "https://www.youtube.com/@dmitrylavrik/videos",
    description: "Полезные материалы по программированию и веб-разработке",
    tags: [],
    preview: "https://yt3.googleusercontent.com/ytc/AIdro_kSO4ok-Ezl1xicKfrqMmRiKCuw_fg8cvpIO2LAXggJox4=s900-c-k-c0x00ffffff-no-rj",
    created_at: "2025-03-07 19:02:06",
    updated_at: "2025-03-07 19:02:10",
    transition_counter: null,
    favorite: false,
  },
  {
    id: "W9QGHV",
    category_id: "ktGDhX",
    title: "VK Лекторий | Москва, VK Fest | 2024 | Павел Островский: Лайки, юмор и семья",
    url: "https://vkvideo.ru/video-165631795_456239998",
    description: "",
    tags: [],
    preview: "",
    created_at: "2025-03-04 22:33:14",
    updated_at: "2025-03-05 20:46:35",
    transition_counter: null,
    favorite: false,
  },
  {
    id: "qczCGW",
    category_id: "ktGDhX",
    title: "СОВСЕМ НЕВЫДУМАННАЯ ИСТОРИЯ (РХ 2024)",
    url: "https://vk.com/video-38080110_456239734",
    description: "",
    tags: [],
    preview: "",
    created_at: "2025-03-02 23:17:07",
    updated_at: "2025-03-02 23:17:16",
    transition_counter: 2,
    favorite: false,
  },
  {
    id: "tqGXiv",
    category_id: "ktGDhX",
    title: "Введение в Node.js. Часть 1. Знакомство с языком - YouTube",
    url: "https://www.youtube.com/watch?v=kkU_Lk8kdms",
    description: "- общие концепция Node- однопоточный или нет, идея event loop- ключевые отличия от Node от PHP- hello world server- почему сейчас я всё чаще выбираю node для...",
    tags: [],
    preview: "https://i.ytimg.com/vi/kkU_Lk8kdms/maxresdefault.jpg",
    created_at: "2025-01-14 18:05:59",
    updated_at: "2025-01-14 18:06:01",
    transition_counter: null,
    favorite: false,
  },
  {
    id: "5kvx9r",
    category_id: "ktGDhX",
    title: "Ошибки приготовления кофе в воронке | Hario v60",
    url: "https://www.youtube.com/watch?v=VJ07UreDgII",
    description: "В этом видео наш оператор и арт-директор Федор впервые готовит кофе в воронке! \n\nИспользуя классику альтернативы — Hario v60, он попробует приготовить напиток по своему рецепту, а если что-то пойдёт не так, Николай внесёт свои корректировки. Или не внесёт?",
    tags: ["ymCVP"],
    preview: "",
    created_at: "2024-12-15 16:50:21",
    updated_at: "2024-12-15 16:50:49",
    transition_counter: null,
    favorite: false,
  },
  {
    id: "arl0na",
    category_id: "ktGDhX",
    title: "КОНЕЦ СВЕТА БЛИЗКО?! Мысли математика и священника. Савватеев и Островский - YouTube",
    url: "https://www.youtube.com/watch?v=hlfjUaCugXw",
    description: "▶︎ Подарите ненужным гаджетам новую жизнь вместе с Авито - https://bit.ly/3VfSvr4?erid=LjN8KL8SV▶︎ Компактный и удобный компрессорный ингалятор Армед для ком...",
    tags: [],
    preview: "https://i.ytimg.com/vi/hlfjUaCugXw/maxresdefault.jpg",
    created_at: "2024-12-02 15:35:20",
    updated_at: null,
    transition_counter: null,
    favorite: false,
  },
  {
    id: "hiqXlv",
    category_id: "ktGDhX",
    title: "BMW k1600gtl полезный и бесполезный тюнинг - YouTube",
    url: "https://www.youtube.com/watch?v=U2oHuW47O8I",
    description: "Всем привет, в сегодняшнем видео я решил рассказать про доработки, которые планирую произвести к сезону со своим мотоциклом BMW k1600gtl. Также будет актуаль...",
    tags: [],
    preview: "https://i.ytimg.com/vi/U2oHuW47O8I/maxresdefault.jpg",
    created_at: "2024-12-02 15:21:44",
    updated_at: null,
    transition_counter: null,
    favorite: false,
  },
  {
    id: "WEhe8e",
    category_id: "ktGDhX",
    title: "Будущие работы: какие навыки будут востребованы - YouTube",
    url: "https://www.youtube.com/watch?v=3N-cOhvR5Ro",
    description: "Программа для тех, кто хочет стать востребованным программистом: https://bit.ly/3w46rv5Закрытое сообщество единомышленников: https://t.me/NextgenSocialBotМой...",
    tags: [],
    preview: "https://i.ytimg.com/vi/3N-cOhvR5Ro/maxresdefault.jpg",
    created_at: "2024-12-02 15:21:34",
    updated_at: null,
    transition_counter: 1,
    favorite: false,
  },
  {
    id: "vdzTF8",
    category_id: "ktGDhX",
    title: "По ту сторону изгороди (мультсериал, 2014) – смотреть онлайн все 10 видео от По ту сторону изгороди (мультсериал, 2014) в хорошем качестве на RUTUBE",
    url: "https://rutube.ru/plst/328979/",
    description: "Смотреть видеоподборку По ту сторону изгороди (мультсериал, 2014) канала  в хорошем качестве без регистрации и совершенно бесплатно на RUTUBE пользователя По ту сторону изгороди (мультсериал, 2014) (328979).",
    tags: [],
    preview: "https://pic.rutubelist.ru/video/1b/42/1b42df069c5e871abfa2ccc7e9e4e02f.jpg",
    created_at: "2024-11-05 12:24:03",
    updated_at: "2024-11-05 12:24:07",
    transition_counter: null,
    favorite: false,
  },
  {
    id: "GD7vMj",
    category_id: "ktGDhX",
    title: "РОСЛА В МОНАСТЫРЕ СЕРГИЯ РОМАНОВА И НЕ МОГЛА УЙТИ.ПОБОИ, МАНИПУЛЯЦИИ И ЛОЖЬ. ПОМОЛЧИМ В КАВЫЧКАХ #22 - YouTube",
    url: "https://www.youtube.com/watch?v=h4s2eGe7TKY",
    description: "Алиса Крыжановская, сегодня популярный блогер, а когда-то – простой подросток, живший в стенах Среднеуральского женского монастыря. Теперь многие забыли о то...",
    tags: [],
    preview: "https://i.ytimg.com/vi/h4s2eGe7TKY/maxresdefault.jpg",
    created_at: "2024-10-24 12:09:31",
    updated_at: "2024-10-24 12:09:33",
    transition_counter: null,
    favorite: false,
  },
  {
    id: "vhZ68X",
    category_id: "ktGDhX",
    title: "Амиран.ИИ Спасение Или Трагедия Для Человека_ Ольга Ускова. | ВКонтакте",
    url: "https://vk.com/video-227461322_456239326",
    description: "",
    tags: [],
    preview: "",
    created_at: "2024-10-18 13:04:07",
    updated_at: "2024-10-18 13:04:20",
    transition_counter: 3,
    favorite: false,
  },
  {
    id: "xA6Imd",
    category_id: "ktGDhX",
    title: "Дебаты:Ричард Докинз и Роуэн Уильямс",
    url: "https://www.youtube.com/watch?v=nGi6sBU-zRc",
    description: "",
    tags: [],
    preview: "",
    created_at: "2024-10-16 11:44:57",
    updated_at: "2024-10-16 11:45:15",
    transition_counter: null,
    favorite: false,
  },
];
