/**
 * Данные для посева закладок
 */

export const DUMMY_BOOKMARK_CATEGORIES = [
  { uid: "wTOx", parent_uid: "", title: "Работа", icon: "", position: 1 },
  { uid: "tVhm", parent_uid: "wTOx", title: "Инструменты", icon: "Folder", position: 1 },
  
  { uid: "IpYb", parent_uid: "", title: "Основное", icon: "", position: 2 },
  { uid: "7i95", parent_uid: "IpYb", title: "Игры", icon: "Rocket", position: 1 },
  { uid: "7LSI", parent_uid: "IpYb", title: "Документация", icon: "Folder", position: 2 },
  { uid: "V8dU", parent_uid: "IpYb", title: "Хочу посмотреть", icon: "Film", position: 3 },
];

export const DUMMY_BOOKMARK_TAGS = [
  { uid: "NSMjl", title: "Playstation" },
  { uid: "ent7g", title: "Node" },
  { uid: "1fFZi", title: "Javascript" },
  { uid: "ymCVP", title: "Кофе" },
  { uid: "XtI6V", title: "AI" },
  { uid: "XoI6V", title: "React" },
];

export const DUMMY_BOOKMARKS = [
  {
    uid: "dSMacJ",
    category_uid: "tVhm",
    title: "Darken Color - mdigi.tools",
    url: "https://mdigi.tools/darken-color",
    description: "Darken a color online. Enter color in rgb, hex, hsl or hsv and get different darker shades of the color.",
    tags: [],
    preview: "",
    created_at: "2025-06-30 02:38:20",
    updated_at: "2025-06-30 02:38:27",
    transition_counter: 1,
    favorite: false,
    in_trash: false,
  },
  {
    uid: "dSMacJr",
    category_uid: "tVhm",
    title: "RGB to HEX Color Converter",
    url: "https://www.rgbtohex.net/",
    description: "Convert RGB color codes to HEX HTML format for use in web design and CSS.  Also converts RGBA to HEX.",
    tags: [],
    preview: "",
    created_at: "2025-06-30 02:38:20",
    updated_at: "2025-06-30 02:38:27",
    transition_counter: 1,
    favorite: true,
    in_trash: false,
  },
  {
    uid: "UIje1I",
    category_uid: "V8dU",
    title: " Nest + Typia = Nestia. Доминация Typescript",
    url: "https://www.youtube.com/watch?v=eAFq35Z6z5I",
    description: "Enjoy the videos and music that you love, upload original content and share it all with friends, family and the world on YouTube.",
    tags: ["1fFZi"],
    preview: "",
    created_at: "2025-06-30 02:37:45",
    updated_at: "2025-06-30 02:38:00",
    transition_counter: 1,
    favorite: false,
    in_trash: false,
  },
  {
    uid: "qRN4eu",
    category_uid: "7i95",
    title: "Grand Theft Auto VI",
    url: "https://stopgame.ru/game/grand_theft_auto_vi",
    description: "Всё об игре Grand Theft Auto VI — описание, обзоры и отзывы, даты выхода, поддерживаемые платформы, официальный сайт и системные требования на нашем сайте",
    tags: ["NSMjl"],
    preview: "",
    created_at: "2026-09-19 21:51:58",
    updated_at: "2026-09-19 21:52:00",
    transition_counter: null,
    favorite: true,
    in_trash: false,
  },
  {
    uid: "qRN4eur",
    category_uid: "7i95",
    title: "Silent Hill 2",
    url: "https://stopgame.ru/game/silent_hill_2",
    description: "Всё об игре Silent Hill 2 — описание, обзоры и отзывы, даты выхода, поддерживаемые платформы, официальный сайт и системные требования на нашем сайте",
    tags: ["NSMjl"],
    preview: "",
    created_at: "2026-09-19 21:51:58",
    updated_at: "2026-09-19 21:52:00",
    transition_counter: null,
    favorite: false,
    in_trash: false,
  },
  {
    uid: "qRN4eua",
    category_uid: "7i95",
    title: "Shazoo - новости игровой индустрии, кино, сериалов, науки и техники",
    url: "https://shazoo.ru",
    description: "Свежие новости игр, кино, сериалов, науки, техники, PC, PS4 и PS5, Xbox и Series X, обзоры, рецензии, руководства, моды, читы, даты выхода игр, системные требования игр.",
    tags: [],
    preview: "",
    created_at: "2026-09-19 21:51:58",
    updated_at: "2026-09-19 21:52:00",
    transition_counter: null,
    favorite: false,
    in_trash: false,
  },
  {
    uid: "NUjbfo",
    category_uid: "V8dU",
    title: "Kodik — AI-редактор, о котором молчат (а зря)",
    url: "https://www.youtube.com/watch?v=lwt2rU7IFwQ",
    description: "Kodik – новая ИИ-IDE, которая дает доступ к расширенному количеству моделей и лимитов.",
    tags: ["XtI6V"],
    preview: "",
    created_at: "2026-09-14 13:51:00",
    updated_at: "2026-09-14 13:51:03",
    transition_counter: 2,
    favorite: false,
    in_trash: false,
  },
  {
    uid: "NUjbfa",
    category_uid: "V8dU",
    title: "Запустил 250 ИИ-агентов одновременно",
    url: "https://www.youtube.com/watch?v=gNsjZvzdGEE",
    description: "Сегодня в видео запускаем толпы ИИ-агентов для решения больших задач. Будем тестить субагентов в Codex, Agent Teams и Dynamic Workflows в Claude Code, плюс запилим кастомную систему для работы с сотнями агентов в сложных параллельно. Будем монтировать видосы, пилить новостные дайджесты и многое другое.",
    tags: ["XtI6V"],
    preview: "",
    created_at: "2026-09-14 13:51:00",
    updated_at: "2026-09-14 13:51:03",
    transition_counter: 2,
    favorite: false,
    in_trash: false,
  },
  {
    uid: "pIDIZR",
    category_uid: "V8dU",
    title: "ReactJS Basics - #1 What is React?",
    url: "https://www.youtube.com/watch?v=JPT3bFIwJYA&list=PL55RiY5tL51oyA8euSROLjMFZbXaV7skS",
    description: "This ReactJS Tutorial dives into the Question what ReactJS actually is and why you might want to use it.",
    tags: ["XoI6V"],
    preview: "",
    created_at: "2025-03-07 19:02:06",
    updated_at: "2025-03-07 19:02:10",
    transition_counter: null,
    favorite: false,
    in_trash: false,
  },
  {
    uid: "tqGXiv",
    category_uid: "V8dU",
    title: "Введение в Node.js. Часть 1. Знакомство с языком - YouTube",
    url: "https://www.youtube.com/watch?v=kkU_Lk8kdms",
    description: "- общие концепция Node- однопоточный или нет, идея event loop- ключевые отличия от Node от PHP- hello world server- почему сейчас я всё чаще выбираю node для...",
    tags: ["ent7g", "1fFZi"],
    preview: "",
    created_at: "2025-01-14 18:05:59",
    updated_at: "2025-01-14 18:06:01",
    transition_counter: null,
    favorite: false,
    in_trash: false,
  },
  {
    uid: "5kvx9r",
    category_uid: "V8dU",
    title: "Ошибки приготовления кофе в воронке | Hario v60",
    url: "https://www.youtube.com/watch?v=VJ07UreDgII",
    description: "В этом видео наш оператор и арт-директор Федор впервые готовит кофе в воронке! \n\nИспользуя классику альтернативы — Hario v60, он попробует приготовить напиток по своему рецепту, а если что-то пойдёт не так, Николай внесёт свои корректировки. Или не внесёт?",
    tags: ["ymCVP"],
    preview: "",
    created_at: "2024-12-15 16:50:21",
    updated_at: "2024-12-15 16:50:49",
    transition_counter: null,
    favorite: false,
    in_trash: false,
  },
  {
    uid: "5kvx9s",
    category_uid: "V8dU",
    title: "Что отличает ХОРОШИЙ кофе от ПЛОХОГО? Рассказываем для новичков в кофейной сфере",
    url: "https://www.youtube.com/watch?v=NcOX7nxRN3I",
    description: "Рассказываю о критериях, по которым можно отличить хороший кофе от плохого, как качество связано с ценой, и можно ли найти хороший кофе в магазине.",
    tags: ["ymCVP"],
    preview: "",
    created_at: "2024-12-15 16:50:21",
    updated_at: "2024-12-15 16:50:49",
    transition_counter: null,
    favorite: false,
    in_trash: false,
  },
  {
    uid: "hiqXlv",
    category_uid: "",
    title: "BMW k1600gtl полезный и бесполезный тюнинг - YouTube",
    url: "https://www.youtube.com/watch?v=U2oHuW47O8I",
    description: "Всем привет, в сегодняшнем видео я решил рассказать про доработки, которые планирую произвести к сезону со своим мотоциклом BMW k1600gtl. Также будет актуаль...",
    tags: [],
    preview: "",
    created_at: "2024-12-02 15:21:44",
    updated_at: null,
    transition_counter: null,
    favorite: false,
    in_trash: false,
  },
  {
    uid: "hiqXlva",
    category_uid: "7LSI",
    title: "React",
    url: "https://react.dev/learn",
    description: "React is the library for web and native user interfaces. Build user interfaces out of individual pieces called components written in JavaScript.",
    tags: ["XoI6V"],
    preview: "",
    created_at: "2024-12-02 15:21:44",
    updated_at: null,
    transition_counter: null,
    favorite: false,
    in_trash: false,
  },
  {
    uid: "hiqXlvb",
    category_uid: "7LSI",
    title: "Vue",
    url: "https://vuejs.org/",
    description: "Vue.js - The Progressive JavaScript Framework",
    tags: [],
    preview: "",
    created_at: "2024-12-02 15:21:44",
    updated_at: null,
    transition_counter: null,
    favorite: false,
    in_trash: false,
  },
  {
    uid: "hiqXlvc",
    category_uid: "7LSI",
    title: "React Aria",
    url: "https://react-aria.adobe.com/",
    description: "Craft world-class accessible components with custom styles.",
    tags: [],
    preview: "",
    created_at: "2024-12-02 15:21:44",
    updated_at: null,
    transition_counter: null,
    favorite: false,
    in_trash: false,
  },
];
